#!/usr/bin/env node
/**
 * Seed Test Data — Host-side CLI shim (plain JS)
 * ─────────────────────────────────────────────────
 *
 * The actual seed runs inside the Expo app because expo-sqlite only works
 * in the device runtime. This CLI prints what *would* be seeded given
 * your flags, and tells you how to run it for real inside the app.
 *
 * Usage:
 *   npm run seed                       # default 14 days
 *   npm run seed -- --days 30          # 30 days of data
 *   npm run seed -- --force            # wipe + reseed
 *   npm run seed -- --days 7 --force   # wipe + reseed 7 days
 */

const args = process.argv.slice(2);

function parseArgs(argv) {
  const opts = { days: 14, force: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--days' || a === '-d') {
      const n = parseInt(argv[++i], 10);
      if (!Number.isNaN(n) && n > 0) opts.days = n;
    } else if (a === '--force' || a === '-f') {
      opts.force = true;
    } else if (a === '--help' || a === '-h') {
      printHelp();
      process.exit(0);
    }
  }
  return opts;
}

function printHelp() {
  console.log(`
Seed Test Data — Arete app
──────────────────────────

Seeds every table in the local SQLite database with realistic dummy data
for UI testing. Generates --days days of history (default 14 = 2 weeks).

IMPORTANT
─────────
expo-sqlite only runs inside the Expo runtime on a device or simulator.
The DB file is NOT accessible from a host-side Node process. To actually
populate the database, open the app and use Settings → Test Data.

This CLI is informational — it prints the seed plan and row estimates.

FLAGS
─────
  -d, --days <n>           Days of history to generate (default: 14)
  -f, --force              Wipe existing seedable rows first
  -h, --help               Show this help

EXAMPLES
────────
  npm run seed                       # default: 14 days, no force
  npm run seed -- --days 30          # 30 days of data
  npm run seed -- --force            # wipe + reseed 14 days
`);
}

function describe(opts) {
  const days = opts.days;
  const force = opts.force;
  const sessions = Math.max(2, Math.round((days / 7) * 3));
  const variable = Math.max(8, Math.round((days / 7) * 8));
  const txns = 3 + 3 + variable; // income + rent + variable
  const journal = Math.min(12, Math.max(3, days));
  const aff = Math.min(7, Math.max(1, days));

  console.log(`
Seed plan
─────────
  days:    ${days}
  force:   ${force ? 'yes (wipe & reseed)' : 'no (skip tables that already have data)'}
  tables:  13 (all seedable tables)

Estimated row counts
────────────────────
  daily_logs            ${days}
  prayer_logs           ${days * 5}      (5 prayers × ${days} days)
  gym_logs              ~${sessions}            (~3 sessions/week)
  nutrition_logs        ${days * 2}     (2 meals/day)
  transactions          ~${txns}     (income + rent + variable)
  timetable             34           (weekly recurring)
  habits                8
  habit_logs            ${days * 8}      (8 habits × ${days} days)
  journal_entries       ~${journal}
  goals                 6
  budget_categories     8
  daily_affirmations    ${aff}
  dashboard_widgets     7

Preserved (never wiped or seeded)
─────────────────────────────────
  prayer_timings    — fetched from Aladhan API at runtime
  ai_providers      — your API keys
  ai_programs       — generated by AI features
  focus_sessions    — from the focus timer

To run this for real
────────────────────
  1. Start the app:  npm start
  2. Open the app on your device or simulator
  3. Go to Settings → Test Data
  4. Tap "Seed Test Data" or "Reset & Seed"
`);
}

const opts = parseArgs(args);
describe(opts);
